image:
  repository: registry.example.com/inventory-back
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: api.example.com
  path: /
  tls:
    enabled: true
    secretName: inventory-back-tls

env:
  ENV: prod
  HTTP_ADDR: ":8080"

config:
  ENV: prod
  HTTP_ADDR: ":8080"
  S3_REGION: "us-east-1"
  S3_FORCE_PATH_STYLE: "true"
  S3_BUCKET: "inventory"
  S3_ENDPOINT: "http://minio.minio.svc:9000"
  S3_PUBLIC_BASE_URL: ""   # opcional (ej: https://cdn.tudominio.com/inventory)

secrets:
  DATABASE_URL: ""
  JWT_SECRET: ""
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""


autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 1
