apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume-postgresql-inventory
  namespace: taller-inventario
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "3Gi"
