apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres-argo
  name: argo-postgres-config
  namespace: {{ .Values.cluster_configuration.namespace | default "argo-workflows" }}
stringData:
  password: {{ .Values.secrets.postgreSQL }}
  username: postgres
type: Opaque