apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql-inventory
  name: postgresql-inventory-config
  namespace: taller-inventario
stringData:
  password: {{ .Values.secrets.postgreSQL }}
  username: postgres
type: Opaque