apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-iventory
  name: postgresql-iventory
  namespace: {{ .Values.cluster_configuration.namespace | default "argo-workflows" }}
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql-iventory