apiVersion: v1
kind: Secret
metadata:
  name: inventory-back-secrets
  namespace: taller-inventario
type: Opaque
stringData:
  DB_USER: "inventory"
  DB_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_USE_OPENSSL_RAND_HEX_32"
  MINIO_ACCESS_KEY: "CHANGE_ME"
  MINIO_SECRET_KEY: "CHANGE_ME"
