apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-back.fullname" . }}
  labels:
    {{- include "inventory-back.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.env.name | quote }}
  HTTP_ADDR: {{ .Values.config.httpAddr | quote }}
  S3_REGION: {{ .Values.config.s3Region | quote }}
  S3_FORCE_PATH_STYLE: {{ ternary "true" "false" .Values.config.s3ForcePathStyle | quote }}
