apiVersion: v1
kind: Secret
metadata:
  name: paas-argo-workflows-minio-secret
  namespace: {{ .Values.cluster_configuration.namespace | default "argo-workflows" }}
  labels:
    app: minio-argo-workflows-sentijobs
type: Opaque
stringData:
  rootUser: admin
  rootPassword: {{ .Values.secrets.minio }}