apiVersion: v1
kind: Service
metadata:
  name: minio-argo-workflows-sentijobs
  namespace: {{ .Values.cluster_configuration.namespace | default "argo-workflows" }}
  labels:
    app: minio-argo-workflows-sentijobs
spec:
  type: ClusterIP
  ports:
    - name: console
      port: 9001
      protocol: TCP
      targetPort: 9001
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio-argo-workflows-sentijobs