name: ci
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Tidy
        run: make tidy-check
      - name: Fmt
        run: make fmt-check
      - name: Install golangci-lint
        run: make lint-install
      - name: Lint
        run: make lint
      - name: Test
        run: go test ./... -race
      - name: Build
        run: make build
