apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-back.fullname" . }}
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.secrets.DATABASE_URL }}"
  JWT_SECRET: "{{ .Values.secrets.JWT_SECRET }}"
  S3_ACCESS_KEY: "{{ .Values.secrets.S3_ACCESS_KEY }}"
  S3_SECRET_KEY: "{{ .Values.secrets.S3_SECRET_KEY }}"
